### ISSUE TITLE
Tabling executions cannot run in Janus but fine through swipl command line

### ISSUE THREAD

**Issue by yangyang-pro** [SWI-Prolog/packages-swipy#6]
Hi,

I am experimenting with Janus on a small-size knowledge graph, which contains a few hundreds triple-like facts:

> measures(molecular_biology_research_technique,quantitative_concept).
isa(embryonic_structure,entity).
isa(hazardous_or_poisonous_substance,chemical_viewed_functionally).
produces(tissue,vitamin).
occurs_in(pathologic_function,age_group).
issue_in(body_space_or_junction,occupation_or_discipline).
isa(social_behavior,activity).
assesses_effect_of(laboratory_procedure,organism_function).
location_of(organization,occupational_activity).
interacts_with(invertebrate,vertebrate).
isa(chemical_viewed_functionally,chemical).
...

And I also have some clauses being defined from these predicates:

> location_of(A,B) :- produces(H,A), co_occurs_with(B,H).
location_of(A,B) :- indicates(B,H), affects(H,A).
location_of(A,B) :- location_of(A,H), diagnoses(B,H).
...

As you see, these rules are recursive, which will run out of memory when I throw a query like `?- location_of(tissue, Y).`

So I just declare all predicates with tabling. Now the query `?- location_of(tissue, Y).` can run with no problems through SWI Prolog CMD.
![image](https://github.com/SWI-Prolog/packages-swipy/assets/70380658/fab33e94-102c-416f-93bd-9ae13e17b312)

However, Janus can never finish running and get the result:
![image](https://github.com/SWI-Prolog/packages-swipy/assets/70380658/71fbd5c6-050b-41bb-8b25-984b60d396eb)

The prolog knowledge base I was using is in the attachment.

Thanks in advance for your response!
[Archive.zip](https://github.com/SWI-Prolog/packages-swipy/files/14266839/Archive.zip)

**Comment by JanWielemaker** [comment]
Sorry for the late reply.    Somehow missed this.    This reproduces.   No clue what is happening yet, but this clearly needs fixing.

**Comment by JanWielemaker** [comment]
The issue is not Janus/Python related.   It can be reproduced using a file test.pl holding

```
:- module(test,
          [ load/0
          ]).

load :-
    consult(user:train),
    consult(user:amie).
```

Now run `swipl test.pl` and then

```
?- load.
<lots of warnings>
?- location_of(tissue, Y).
<hangs>
```
It is not yet clear to me why this works on the toplevel, but there are dubious things going on.   Looking at isa/2, we find a dynamic and tabling declaration in `train.pl`, facts in `train.pl` and rules in `amie.pl`.   We get a whole lot of discontiguous warnings, but also

```
Warning: /home/janw/src/swipl-devel/build.debug/amie.pl:701:
Warning:    Redefined static procedure isa/2
Warning:    Previously defined at /home/janw/src/swipl-devel/build.debug/train.pl:102
```

Which means you loose part of the definition.    If you want clauses from multiple files, you should define the predicates using `multifile/1`.    Normally, `table/1` declarations should be before the clauses and defining predicates as both dynamic and tabled is not very meaningful.     Tabled code is normally static and dynamic code that is used by tabled predicates must be defined as _incremental_.  See https://www.swi-prolog.org/pldoc/man?section=tabling-incremental.

Note that discontiguous warnings may be silenced per predicate or for the whole file using

    :- style_check(-discontiguous).

Another way to spread code over multiple files is to add a `load.pl` (or whatever) file and use `include/1`, which performs a _lexical include_.

I'm pretty sure that following this will resolve the issue for you.    I'll still do a little search why consulting the code into `user` from a module (which is also what happens with `janus.consult()`) is different from just loading.   That should not be the case.

**Comment by JanWielemaker** [comment]
I examined this a little closer.    It all depends a little on how exactly you load the code due to the errors.    If you avoid the errors by removing the dynamic, use `:- style_check(-discontiguous).` and `:- include(amie).` from `trans.pl` at the bottom, it no longer terminates.    Well, it is just slow and uses too much memory.    Running the same in XSB Prolog gets a result in several minutes,  using about 5gb memory.   Earlier termination is due to the fact that a significant part of the program is removed due to redefinition.

SWI-Prolog's tabling can't deal with this within the 128Gb of my desktop.    The problem is a huge number of variants that require to be _suspended_.    SWI-Prolog's continuation based approach seems to use considerable more memory for handling this case.    The challenge is probably to rewrite the code in a way that reduces the number of required suspensions.    How to do that is a more suitable topic for SWI-Prolog's Discourse forum.     I may have some ideas, but not sure whether that will work out.   Alternatively, use XSB.

In any case, this is not a Janus/Python issue nor a real "bug".
